import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import TranslationProvider from "@/providers/TranslationProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import { Toaster } from "sonner";
import AuthProvider from "@/providers/AuthProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="customScroll bg-bg-1 lg:bg-bg-2">
      <body className={montserrat.className}>
        <TranslationProvider>
          <ThemeProvider>
            <AuthProvider>
              {children}
              <Toaster />
            </AuthProvider>
          </ThemeProvider>
        </TranslationProvider>
      </body>
    </html>
  );
}
