import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import TranslationProvider from '@/providers/TranslationProvider';
import ThemeProvider from '@/providers/ThemeProvider';

const montserrat = Montserrat({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<TranslationProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</TranslationProvider>
			</body>
		</html>
	);
}
